# Generated by Django 5.0.2 on 2024-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen_principal',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, default='img/hero-banner.jpg', null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, default='img/hero-banner.jpg', null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='resumen_2',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='producto',
            name='resumen',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
