# Generated by Django 5.0.2 on 2024-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='../static/img/banner_productos1.png', upload_to='noticias'),
        ),
    ]
