# Generated by Django 5.0.2 on 2024-03-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria_noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.categoria'),
        ),
        migrations.AddField(
            model_name='comment',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='noticias.noticia'),
        ),
    ]
