# Generated by Django 5.0.2 on 2024-02-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(max_length=450),
        ),
    ]
